### PR TITLE
Added accumulated dynamic point clouds to nearest neighbor search

### PR DESCRIPTION
**Pull request by finnSartoris**

### CODE REVIEW

**Comment by daniel-bogdoll** [comment]
Hi @JulesSanchez, did you already find the time to review the PR by @finnSartoris? The solutions greatly improves the recovery since it also includes all dynamic objects :)

**Comment by JulesSanchez** [comment]
Hi, Sadly I was extremely busy with my research recently. I'll try to review it asap. Sorry for the delay.

**Comment by daniel-bogdoll** [comment]
No worries! Hope your research is going well, and thanks for open-sourcing your work, helped a lot! :)

**Comment by daniel-bogdoll** [comment]
Hey @JulesSanchez, hope you had a great week :) Did you find the time to review the PR? Finn is presenting his work next week and it would be great if his additions would be easily accessible :)

Have a great weekend!

**Comment by JulesSanchez** [comment]
Hey, I'll do it over the weed-end then !

**Review by JulesSanchez — APPROVED** [review]

**Comment by JulesSanchez** [comment]
Done, great work and nice visualization in the ReadMe.

**Pull request merged**
